name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Primeiro
      id: primeiro
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Primeiro
        setup-command: gcc tarefas/tarefa1.c -o tarefa1.o
        command: "./tarefa1.o"
        input: '3'
        expected-output: '28.26'
        comparison-method: contains
        timeout: 3
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        PRIMEIRO_RESULTS: "${{steps.primeiro.outputs.result}}"
      with:
        runners: primeiro
